sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    options:
        form_type: horizontal
        use_icheck: false

    security:
        handler: sonata.admin.security.handler.role
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT

    dashboard:
        groups:
            User:
                items:
                    - app.admin.user

        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [ User  ]
