services:
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User", label: "User" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~

    app.admin.demo:
        class: AppBundle\Admin\DemoAdmin
        arguments: [~, AppBundle\Entity\Demo, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Demo }
